const types = {
  ADD_ITEM_START: "ADD_ITEM_START",
  ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",

  DELETE_ITEM_START: "DELETE_ITEM_START",
  DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",

  SEARCH_START: "SEARCH_START",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
};

export default types;
